# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='opis'),
        ),
    ]
