# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20170622_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='datetime',
        ),
        migrations.AddField(
            model_name='screening',
            name='view_hour',
            field=models.IntegerField(choices=[(0, '8:00'), (1, '8:30'), (2, '9:00'), (3, '9:30'), (4, '10:00'), (5, '10:30'), (6, '11:00'), (7, '11:30'), (8, '12:00'), (9, '12:30'), (10, '13:00'), (11, '13:30'), (12, '14:00'), (13, '14:30'), (14, '15:00'), (15, '15:30'), (16, '16:00'), (17, '16:30'), (18, '17:00'), (19, '17:30'), (20, '18:00'), (21, '18:30'), (22, '19:00'), (23, '19:30'), (24, '20:00'), (25, '20:30')], default=0),
        ),
    ]
