# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_evaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='text',
            new_name='opinion',
        ),
    ]
