# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20170626_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(max_length=1000)),
                ('author', models.TextField(default='Anonymous', max_length=100)),
                ('mark', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****'), (6, '******')], default=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seans', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.Movie')),
            ],
            options={
                'verbose_name_plural': 'evaluations',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='author',
            field=models.TextField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='mark',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****'), (6, '******')], default=6),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='seans',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.Movie'),
        ),
    ]
